python: can't open file '/home/pi/Desktop/RaspiLight/bin/allumer_eteindre.py': [Errno 2] No such file or directory
python: can't open file '/home/pi/Desktop/RaspiLight/bin/allumer_eteindre.py': [Errno 2] No such file or directory
python: can't open file '/home/pi/Desktop/RaspiLight/bin/allumer_eteindre.py': [Errno 2] No such file or directory
python: can't open file '/home/pi/Desktop/RaspiLight/bin/allumer_eteindre.py': [Errno 2] No such file or directory
python: can't open file '/home/pi/Desktop/RaspiLight/bin/allumer_eteindre.py': [Errno 2] No such file or directory
python: can't open file '/var/www/html/cgi-bin/allumer_eteindre.py': [Errno 2] No such file or directory
python: can't open file '/var/www/html/cgi-bin/allumer_eteindre.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'num'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'numero'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/RaspiLight/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'parm[1]'
Traceback (most recent call last):
  File "/var/www/LightPi/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/LightPi/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/LightPi/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/LightPi/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/var/www/LightPi/bin/allumer_eteindre.py", line 4, in <module>
    num = int(sys.argv[1])
IndexError: list index out of range
